import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles(() => ({
  page: {
     backgroundColor: "#FFFFFF",
    padding: "30px",
    display: "flex",
    justifyContent: "center",
    minHeight: "100vh",
    paddingTop: "10px",
  },
  hero: {
    alignItems: "center",
    background: "#162a46",
    borderRadius: 12,
    color: "white",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 18,
    overflow: "hidden",
    padding: "28px 30px",
    "@media (max-width: 700px)": {
      alignItems: "flex-start",
      flexDirection: "column",
      gap: 20,
    },
  },
  eyebrow: {
    color: "#89d4b1",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  heroTitle: {
    fontSize: "clamp(24px, 3vw, 38px)",
    fontWeight: 800,
    letterSpacing: -0.5,
    lineHeight: 1.1,
    marginTop: 8,
  },
  heroCopy: {
    color: "#c3d0df",
    fontSize: 14,
    marginTop: 10,
    maxWidth: 480,
  },
  periodSelect: {
    background: "white",
    borderRadius: 5,
    minWidth: 260,
  },
  selectIcon: {
    color: "#55708f",
    fontSize: 19,
    marginLeft: 8,
  },
  summaryGrid: {
    marginBottom: 18,
  },
  summaryCard: {
    border: "1px solid #e6ebf2",
    borderRadius: 10,
    boxShadow: "0 4px 16px rgba(21, 46, 74, 0.04)",
    minHeight: 145,
    padding: "17px 18px",
  },
  cardTop: {
    alignItems: "center",
    display: "flex",
    gap: 9,
  },
  cardLabel: {
    color: "#617188",
    fontSize: 13,
    fontWeight: 700,
  },
  metricIcon: {
    alignItems: "center",
    borderRadius: 8,
    display: "flex",
    height: 31,
    justifyContent: "center",
    width: 31,
  },
  metricValue: {
    color: "#1b2b42",
    fontSize: 22,
    fontWeight: 800,
    marginTop: 19,
  },
  cardNote: {
    fontSize: 11,
    fontWeight: 700,
    marginTop: 9,
  },
  contentGrid: {
    marginBottom: 18,
  },
  panel: {
    background: "white",
    border: "1px solid #e6ebf2",
    borderRadius: 10,
    boxShadow: "0 4px 16px rgba(21, 46, 74, 0.04)",
    padding: 20,
    marginBottom: 18,
    width: "100%",
  },
  panelHeader: {
    alignItems: "flex-start",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  panelTitle: {
    color: "#20314a",
    fontSize: 17,
    fontWeight: 800,
  },
  panelSub: {
    color: "#8290a3",
    fontSize: 12,
    marginTop: 4,
  },
  healthyChip: {
    background: "#e8f6ef !important",
    color: "#147d64 !important",
    fontSize: "11px !important",
    fontWeight: "700 !important",
  },
  filterIcon: {
    color: "#91a0b3",
  },
  cashChart: {
    borderTop: "1px solid #eef1f5",
    paddingTop: 14,
  },
  chartLegend: {
    color: "#7c8a9e",
    display: "flex",
    fontSize: 11,
    gap: 18,
    marginBottom: 12,
  },
  incomeLegend: {
    background: "#287d68",
    borderRadius: 2,
    display: "inline-block",
    height: 7,
    marginRight: 5,
    width: 7,
  },
  expenseLegend: {
    background: "#e5aa78",
    borderRadius: 2,
    display: "inline-block",
    height: 7,
    marginRight: 5,
    width: 7,
  },
  chartRow: {
    alignItems: "center",
    color: "#718096",
    display: "grid",
    fontSize: 11,
    gap: 9,
    gridTemplateColumns: "45px 1fr 85px",
    margin: "17px 0",
  },
  chartTrack: {
    background: "#f0f3f7",
    borderRadius: 4,
    height: 18,
    position: "relative",
  },
  incomeBar: {
    background: "#287d68",
    borderRadius: 4,
    height: 8,
    left: 0,
    position: "absolute",
    top: 2,
  },
  expenseBar: {
    background: "#e5aa78",
    borderRadius: 4,
    bottom: 2,
    height: 8,
    left: 0,
    position: "absolute",
  },
  compareLine: {
    borderTop: "1px solid #eef1f5",
    color: "#7d8b9e",
    display: "flex",
    fontSize: 12,
    gap: 35,
    justifyContent: "flex-end",
    paddingTop: 15,
  },
  expenseList: {
    marginTop: 26,
  },
  expenseItem: {
    alignItems: "center",
    borderBottom: "1px solid #f0f2f6",
    display: "flex",
    fontSize: 12,
    justifyContent: "space-between",
    padding: "11px 0",
  },
  expenseName: {
    alignItems: "center",
    color: "#526176",
    display: "flex",
    gap: 8,
  },
  categoryDot: {
    background: "#e5aa78",
    borderRadius: "50%",
    height: 8,
    width: 8,
  },
  expenseTotal: {
    color: "#243650",
    display: "flex",
    fontSize: 13,
    fontWeight: 800,
    justifyContent: "space-between",
    marginTop: 14,
  },
  filters: {
    marginBottom: 18,
  },
  filterField: {
    minWidth: 150,
    "@media (max-width: 700px)": {
      width: "100%",
    },
  },
  clearButton: {
    color: "#66758a !important",
    fontSize: "12px !important",
    minWidth: "auto !important",
    textTransform: "none !important",
  },
  tableHead: {
    background: "#f7f9fc",
    color: "#718096 !important",
    fontSize: "11px !important",
    fontWeight: "800 !important",
    textTransform: "uppercase",
  },
  incomeType: {
    alignItems: "center",
    color: "#147d64",
    display: "flex",
    fontSize: 12,
    fontWeight: 700,
    gap: 4,
  },
  expenseType: {
    alignItems: "center",
    color: "#c65b35",
    display: "flex",
    fontSize: 12,
    fontWeight: 700,
    gap: 4,
  },
  categoryChip: {
    background: "#f0f3f7 !important",
    color: "#53647a !important",
    fontSize: "11px !important",
  },
  statusChip: {
    background: "#e8f6ef !important",
    color: "#147d64 !important",
    fontSize: "11px !important",
  },
  warningChip: {
    background: "#fff4df !important",
    color: "#ad6e14 !important",
    fontSize: "11px !important",
  },
  descriptionCell: {
    color: "#34445a !important",
    fontWeight: "600 !important",
  },
  amountCell: {
    color: "#243650 !important",
    fontWeight: "800 !important",
    whiteSpace: "nowrap",
  },
  printButton: {
    border: "1px solid #dce4ed !important",
    color: "#34445a !important",
    minWidth: "auto !important",
    textTransform: "none !important",
  },
  printOnly: {
    display: "none",
  },
}));